<div class="container mx-auto py-8 px-4">
    <h1 class="text-3xl font-bold mb-4">Privacy Policy</h1>
    <p class="text-gray-700 mb-4">Effective Date: 24/06/2024</p>
  
    <p class="text-gray-700 mb-8">
      CodeCarona is committed to protecting your privacy and the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and store your information when you use our peer-to-peer file-sharing application ("NeighborHoodShare" or "the Application").
    </p>
  
    <h2 class="text-2xl font-bold mb-4">Information We Collect</h2>
  
    <ul class="list-disc pl-4 mb-8">
      <li class="text-gray-700">Peer ID: A unique identifier generated by the application to establish connections within the network. You choose to share this ID with others to connect and share files.</li>
      <li class="text-gray-700">Usage Data: We may collect anonymous usage data about your interaction with the application, such as features used, frequency of use, and any error reports. This data helps us improve the application and user experience.</li>
    </ul>
  
    <h2 class="text-2xl font-bold mb-4">How We Use Your Information</h2>
  
    <ul class="list-disc pl-4 mb-8">
      <li class="text-gray-700">To operate and maintain NeighborHoodShare</li>
      <li class="text-gray-700">To connect you with other users on the network (based on shared Peer IDs)</li>
      <li class="text-gray-700">To improve the application and user experience</li>
      <li class="text-gray-700">To analyze usage trends and identify potential improvements</li>
      <li class="text-gray-700">To comply with legal obligations</li>
    </ul>
  </div>
  